workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - email_credentials # Elimina si no usas variables seguras
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      # Paso 1: Limpieza de paquetes y APKs previas
      - name: Clean Flutter project
        script: |
          flutter clean
          rm -rf build/app/outputs/flutter-apk/*.apk
      # Paso 2: Obtener paquetes
      - name: Get Flutter packages
        script: |
          flutter pub get
      # Paso 3: Analizar el código
      - name: Analyze code
        script: |
          flutter analyze
      # Paso 4: Ejecutar pruebas
      - name: Run unit tests
        script: |
          flutter test
      # Paso 5: Construir la APK
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - aalan_666@yahoo.com
        notify:
          success: true
          failure: true