name: CI
on:
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: ["main", "develop"]

jobs:
  ejecutar_pruebas:
    name: Ejecutar pruebas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # ✅ Versión actual de Flutter
      - name: Install dependencies
        run: flutter pub get
      - name: Clean
        run: flutter clean
      - name: Analyze
        run: flutter analyze
      - name: Test
        run: flutter test

  build_android:
    name: Build Android
    needs: [ejecutar_pruebas]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # ✅ Actualizado
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release

  build_ios:
    name: Build iOS
    needs: [ejecutar_pruebas]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # ✅ También aquí
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release --no-codesign
